apiVersion: v1
kind: Namespace
metadata:
  name: pmem-csi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: pmem-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: pmem-csi-intel-com-controller
  namespace: pmem-csi
- kind: ServiceAccount
  name: pmem-csi-intel-com-webhooks
  namespace: pmem-csi
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: pmem-csi
spec:
  targetNamespaces:
  - pmem-csi
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: openshift-marketplace
spec:
  displayName: Upstream Operatorhub.io Catalog
  image: quay.io/operatorhubio/catalog:latest
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pmem-csi
  namespace: pmem-csi
spec:
  channel: alpha
  name: pmem-csi-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
