---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: openshift-marketplace
spec:
  image: quay.io/operatorhubio/catalog:latest
  displayName: Upstream Operatorhub.io Catalog
  publisher: OperatorHub.io
  sourceType: grpc
